language: node_js
node_js:
    - "6"
    - "lts/*"                # Active LTS release
    - "node"                 # Latest stable release
script: 'make coverage'
after_success: 'make report-coverage'
