name: CI
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  test:
    name: Use Node.js with ${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [lts/-2, lts/-1, lts/*]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: make clean
      - run: make coverage
      - run: make report-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
